# Generated by Django 5.2 on 2025-05-06 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='location.region')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_number', models.PositiveIntegerField()),
                ('school_type', models.CharField(choices=[('general', "Umumta'lim"), ('specialized', 'Ixtisoslashtirilgan'), ('jasorat', '"Jasorat" maktabi')], max_length=20)),
                ('director_full_name', models.CharField(max_length=255)),
                ('geo_location', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.region')),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'district'], name='location_sc_region__dd5f9c_idx'), models.Index(fields=['school_number'], name='location_sc_school__c8cfa8_idx')],
            },
        ),
    ]
