# Generated by Django 5.2 on 2025-05-06 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnfl', models.CharField(db_index=True, max_length=14, unique=True)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(db_index=True)),
                ('birth_place', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('graduated_university', models.CharField(max_length=255)),
                ('military_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification_level', models.CharField(max_length=255)),
                ('qualification_place', models.CharField(max_length=255)),
                ('qualification_date', models.DateField()),
                ('military_rank_date', models.DateField(blank=True, null=True)),
                ('experience_years', models.IntegerField()),
                ('is_vacant', models.BooleanField(db_index=True, default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='location.school')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
