# Generated by Django 5.2 on 2025-05-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
    ]
