# Generated by Django 5.2 on 2025-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egov_api", "0001_initial"),
        ("users", "0002_remove_userprofile_department_userprofile_oblast_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="birth_place",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="oblast",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Viloyat",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="region",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Tuman",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["oblast"], name="users_userp_oblast_39a310_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["region"], name="users_userp_region_b6f82c_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["school"], name="users_userp_school__0fe292_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["oblast", "region"], name="users_userp_oblast_37beed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["school", "region"], name="users_userp_school__0a997c_idx"
            ),
        ),
    ]
