# Generated by Django 5.2 on 2025-05-14 05:54

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('users', '0003_remove_userprofile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='jshir',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified_by_external_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pinfl',
            field=models.CharField(default=builtins.print, max_length=14, unique=True, verbose_name='PINFL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Yashash manzili'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.school', verbose_name='Maktabi'),
        ),
    ]
