# Generated by Django 5.2 on 2025-05-21 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egov_api", "0001_initial"),
        ("material_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Amalda mavjud"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_status",
                        to="egov_api.school",
                        verbose_name="Maktab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jihoz holati",
                "verbose_name_plural": "Jihoz holatlari",
                "db_table": "classroom_equipments",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Jihoz nomi")),
                (
                    "standard_quantity",
                    models.PositiveIntegerField(verbose_name="Shtat bo‘yicha soni"),
                ),
            ],
            options={
                "verbose_name": "Jihoz nomi",
                "verbose_name_plural": "Jihozlar",
                "db_table": "equipments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="OMB mezoni"
                    ),
                ),
            ],
            options={
                "verbose_name": "O`quv moddiy baza",
                "verbose_name_plural": "O`quv moddiy baza",
                "db_table": "material_base",
            },
        ),
        migrations.CreateModel(
            name="SchoolMaterialBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=False, verbose_name="Mavjudligi"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_material_base",
                        to="material_base.materialbase",
                        verbose_name="Baza",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_base",
                        to="egov_api.school",
                        verbose_name="Maktab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maktab o`quv moddiy bazasi",
                "verbose_name_plural": "Maktab o`quv moddiy bazasi",
                "db_table": "school_material_base",
                "unique_together": {("school", "material")},
            },
        ),
        migrations.DeleteModel(
            name="InventoryItem",
        ),
        migrations.AddField(
            model_name="classroomequipment",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="material_base.equipment",
                verbose_name="Maktab jihozlari",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroomequipment",
            unique_together={("school", "equipment")},
        ),
    ]
