# Generated by Django 5.2 on 2025-05-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_base", "0003_alter_equipment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmaterialbase",
            name="is_available",
            field=models.BooleanField(null=True, verbose_name="Mavjudligi"),
        ),
    ]
