# Generated by Django 5.2 on 2025-06-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("egov_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Musobaqa nomi"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("school", "Maktab"),
                            ("region", "Tuman"),
                            ("oblast", "Viloyat"),
                            ("republic", "Respublika"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="egov_api.school",
                        verbose_name="Tashkilotchi maktab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Musobaqa",
                "verbose_name_plural": "Musobaqalar",
            },
        ),
        migrations.CreateModel(
            name="CompetitionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("class", "Sinf"),
                            ("school", "Maktab"),
                            ("mahalla", "Mahalla yoshlari"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_name",
                    models.CharField(
                        blank=True,
                        help_text="Mahalla yoki tashqi nom",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="competition.competition",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="egov_api.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishtirokchi",
                "verbose_name_plural": "Ishtirokchilar",
            },
        ),
    ]
