# Generated by Django 5.2 on 2025-05-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.PositiveIntegerField(db_column='external_id', unique=True, verbose_name='Tashqi ID')),
                ('inn', models.CharField(db_column='inn', max_length=20, unique=True, verbose_name='INN')),
                ('name', models.CharField(db_column='name', db_index=True, max_length=200, verbose_name='Maktab nomi')),
                ('short_name', models.CharField(blank=True, db_column='short_name', db_index=True, max_length=200, verbose_name='Qisqa nomi')),
                ('address', models.TextField(blank=True, db_column='address', verbose_name='Manzil')),
                ('region_id', models.PositiveIntegerField(db_column='region_id', verbose_name='TumanID')),
                ('region', models.CharField(blank=True, db_column='region', db_index=True, max_length=100, verbose_name='Tuman')),
                ('region_soato_code', models.CharField(blank=True, db_column='region_soato_code', max_length=20, verbose_name='Tuman kodi')),
                ('oblast_id', models.PositiveIntegerField(db_column='oblast_id', verbose_name='OblastID')),
                ('oblast', models.CharField(blank=True, db_column='oblast', db_index=True, max_length=100, verbose_name='Viloyat')),
                ('oblast_soato_code', models.CharField(blank=True, db_column='oblast_soato_code', max_length=20, verbose_name='Viloyat kodi')),
                ('director', models.CharField(blank=True, db_column='director', max_length=255, verbose_name='Direktor')),
                ('contact_info', models.CharField(blank=True, db_column='contact_info', max_length=255, verbose_name='Tel raqami')),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=9, max_digits=12, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=9, max_digits=12, null=True, verbose_name='Uzunlik')),
            ],
            options={
                'verbose_name': 'Maktab',
                'verbose_name_plural': 'Maktablar',
                'db_table': 'emaktab_schools',
                'indexes': [models.Index(fields=['ext_id'], name='emaktab_sch_externa_54d550_idx'), models.Index(fields=['inn'], name='emaktab_sch_inn_dd90b3_idx'), models.Index(fields=['region_id'], name='emaktab_sch_region__c337d3_idx'), models.Index(fields=['oblast_id'], name='emaktab_sch_oblast__fd9af9_idx'), models.Index(fields=['region_soato_code'], name='emaktab_sch_region__1cf626_idx'), models.Index(fields=['oblast_soato_code'], name='emaktab_sch_oblast__1dd1ef_idx'), models.Index(fields=['oblast', 'region', 'name'], name='emaktab_sch_oblast_b33c9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinfl', models.CharField(db_column='pinfl', db_index=True, max_length=14, unique=True, verbose_name='PINFL')),
                ('full_name', models.CharField(db_column='full_name', max_length=255, verbose_name='F.I.SH.')),
                ('birth_date', models.DateField(db_column='birth_date', verbose_name='Tug`ilgan sana')),
                ('gender', models.CharField(db_column='gender', max_length=10, verbose_name='Jinsi')),
                ('document_series', models.CharField(blank=True, db_column='doc_series', max_length=10, verbose_name='Hujjat seriyasi')),
                ('document_number', models.CharField(blank=True, db_column='doc_number', max_length=20, verbose_name='Hujjat raqami')),
                ('mfy_name', models.CharField(blank=True, db_column='mfy_name', max_length=255, verbose_name='MFY nomi')),
                ('grade', models.CharField(db_column='grade', db_index=True, max_length=20, verbose_name='Sinfi')),
                ('class_letter', models.CharField(db_column='class_letter', max_length=20, verbose_name='Sinf harfi')),
                ('school_year', models.CharField(db_column='school_year', max_length=20, verbose_name='o`quv yili')),
                ('address', models.TextField(blank=True, db_column='address', verbose_name='Yashash manzili')),
                ('oblast_id', models.PositiveIntegerField(blank=True, db_column='oblast_id', null=True, verbose_name='Viloyat ID')),
                ('region_id', models.PositiveIntegerField(blank=True, db_column='region_id', null=True, verbose_name='Tuman ID')),
                ('school_grade_id', models.PositiveIntegerField(blank=True, db_column='school_grade_id', null=True, verbose_name='Sinflar ID')),
                ('org_school_grade_id', models.PositiveIntegerField(blank=True, db_column='org_school_grade_id', null=True, verbose_name='Sinf (harf) ID')),
                ('school_year_id', models.PositiveIntegerField(blank=True, db_column='school_year_id', null=True, verbose_name='O‘quv yili ID')),
                ('mfy_id', models.PositiveIntegerField(blank=True, db_column='mfy_id', null=True, verbose_name='MFY ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Yaratilgan vaqti')),
                ('school', models.ForeignKey(db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='egov_api.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'O`quvchi',
                'verbose_name_plural': 'O`quvchilar',
                'db_table': 'emaktab_students',
                'indexes': [models.Index(fields=['grade'], name='emaktab_stu_grade_2cdbdc_idx'), models.Index(fields=['pinfl'], name='emaktab_stu_pinfl_39ce95_idx'), models.Index(fields=['school'], name='emaktab_stu_school__99b80f_idx'), models.Index(fields=['oblast_id'], name='emaktab_stu_oblast__1dbab5_idx'), models.Index(fields=['region_id'], name='emaktab_stu_region__6ee92c_idx'), models.Index(fields=['school_year_id'], name='emaktab_stu_school__16f697_idx'), models.Index(fields=['org_school_grade_id'], name='emaktab_stu_org_sch_ffd1a3_idx'), models.Index(fields=['mfy_id'], name='emaktab_stu_mfy_id_3c5764_idx')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinfl', models.CharField(db_column='pinfl', max_length=14, unique=True, verbose_name='PINFL')),
                ('first_name', models.CharField(db_column='first_name', max_length=55, verbose_name='Ismi')),
                ('last_name', models.CharField(db_column='last_name', max_length=55, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, db_column='middle_name', max_length=55, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(db_column='birth_date', verbose_name='Tug`ilgan sana')),
                ('gender', models.CharField(db_column='gender', max_length=10, verbose_name='Jinsi')),
                ('document_series', models.CharField(blank=True, db_column='doc_series', max_length=10, verbose_name='Hujjat seriyasi')),
                ('document_number', models.CharField(blank=True, db_column='doc_number', max_length=20, verbose_name='Hujjat raqami')),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, verbose_name='Tuman')),
                ('oblast', models.CharField(blank=True, db_column='oblast', max_length=100, verbose_name='Viloyat')),
                ('organisation_id', models.PositiveIntegerField(db_column='organisation_id', verbose_name='Maktab ID')),
                ('organisation_name', models.CharField(db_column='organisation_name', max_length=255, verbose_name='Maktab nomi')),
                ('position_name', models.CharField(db_column='position_name', max_length=255, verbose_name='Lavozimi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Yaratilgan vaqti')),
                ('school', models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='egov_api.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'CHQBT rahbari',
                'verbose_name_plural': 'CHQBT rahbarlari',
                'db_table': 'mygov_teachers',
                'indexes': [models.Index(fields=['pinfl'], name='mygov_teach_pinfl_c0915a_idx'), models.Index(fields=['school'], name='mygov_teach_school__1c7b36_idx'), models.Index(fields=['organisation_id'], name='mygov_teach_organis_b6df4b_idx'), models.Index(fields=['region'], name='mygov_teach_region_ab4742_idx'), models.Index(fields=['oblast'], name='mygov_teach_oblast_2e1752_idx')],
            },
        ),
    ]
