# Generated by Django 5.2 on 2025-06-12 04:54

import django.db.models.deletion
import training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("egov_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Mashg‘ulot nomi"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("theoretical", "Nazariy"), ("practical", "Amaliy")],
                        max_length=20,
                        verbose_name="Mashg‘ulot turi",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=training.models.training_image_upload_path,
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
            ],
            options={
                "verbose_name": "Mashg‘ulot",
                "verbose_name_plural": "Mashg‘ulotlar",
            },
        ),
        migrations.CreateModel(
            name="ClassTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Mashg‘ulot o‘tkazilgan sana")),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Qo‘shimcha izoh"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="egov_api.school",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="training.training",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sinf mashg‘uloti",
                "verbose_name_plural": "Sinf mashg‘ulotlari",
            },
        ),
    ]
